"""
backfill_metadata.py
────────────────────
One-time repair script:
  1. Patches any metadata JSON that is missing the 'shortcode' field
     (derives it from the filename).
  2. Updates the hashtag index file so it includes shortcodes for ALL
     metadata files found on disk — not just the ones that were tracked
     during a completed run.

Run once after a cancelled scrape to make the engagement matrix accurate:
    python backfill_metadata.py
"""
import os
import glob
import json
from datetime import datetime

METADATA_DIR  = os.path.join("scraped_data", "metadata")
INDEX_PATTERN = os.path.join("scraped_data", "*_index.json")


def patch_shortcode_fields():
    """Ensure every metadata file has a 'shortcode' key."""
    patched = 0
    for fp in glob.glob(os.path.join(METADATA_DIR, "*.json")):
        try:
            with open(fp, encoding="utf-8") as f:
                data = json.load(f)
            if not data.get("shortcode"):
                sc = os.path.basename(fp).replace("_metadata.json", "")
                data["shortcode"] = sc
                with open(fp, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=4, ensure_ascii=False)
                print(f"  Patched shortcode → {sc}")
                patched += 1
        except Exception as e:
            print(f"  ERROR patching {fp}: {e}")
    print(f"Patched {patched} file(s).")


def rebuild_index_from_disk():
    """
    For each *_index.json, add any shortcodes found in the metadata directory
    that are not already in the index.
    Also creates a synthetic index if none exists.
    """
    # Collect all shortcodes that have metadata files
    disk_shortcodes = set()
    for fp in glob.glob(os.path.join(METADATA_DIR, "*.json")):
        sc = os.path.basename(fp).replace("_metadata.json", "")
        disk_shortcodes.add(sc)

    print(f"\nShortcodes with metadata on disk: {len(disk_shortcodes)}")

    idx_files = glob.glob(INDEX_PATTERN)

    if not idx_files:
        # No index at all — create a generic one so the matrix can read all metadata
        print("  No index file found. Creating synthetic 'all_posts_index.json'...")
        synthetic = {
            "hashtag":    "all_posts",
            "shortcodes": sorted(disk_shortcodes),
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "note": "Auto-generated by backfill_metadata.py",
        }
        out = os.path.join("scraped_data", "all_posts_index.json")
        with open(out, "w", encoding="utf-8") as f:
            json.dump(synthetic, f, indent=4, ensure_ascii=False)
        print(f"  Created: {out}")
        return

    for idx_path in idx_files:
        try:
            with open(idx_path, encoding="utf-8") as f:
                idx = json.load(f)
            existing = set(idx.get("shortcodes", []))
            missing  = disk_shortcodes - existing
            if missing:
                idx["shortcodes"] = sorted(existing | disk_shortcodes)
                idx["last_backfilled"] = datetime.utcnow().isoformat() + "Z"
                with open(idx_path, "w", encoding="utf-8") as f:
                    json.dump(idx, f, indent=4, ensure_ascii=False)
                print(f"  Added {len(missing)} missing shortcode(s) to {os.path.basename(idx_path)}")
            else:
                print(f"  {os.path.basename(idx_path)} is already up to date.")
        except Exception as e:
            print(f"  ERROR reading {idx_path}: {e}")


if __name__ == "__main__":
    print("=" * 55)
    print("  Backfill Metadata Repair Script")
    print("=" * 55)

    if not os.path.isdir(METADATA_DIR):
        print(f"ERROR: {METADATA_DIR} not found. Run the scraper first.")
        raise SystemExit(1)

    print("\n[1/2] Patching missing shortcode fields...")
    patch_shortcode_fields()

    print("\n[2/2] Rebuilding index files from disk...")
    rebuild_index_from_disk()

    print("\n[3/3] Re-running engagement matrix on all available data...")
    try:
        from engagement_matrix import build_engagement_matrix, print_summary, save_report, save_csv
        report = build_engagement_matrix()
        if report["hashtags"]:
            print_summary(report)
            jp = save_report(report)
            cp = save_csv(report)
            print(f"💾 JSON → {jp}")
            print(f"💾 CSV  → {cp}")
        else:
            print("  No data to matrix.")
    except Exception as e:
        print(f"  Matrix error: {e}")

    print("\nDone.")
