"""Configuration constants for the Instagram scraper."""

# ──────────────────────────── Mode Selection ────────────────────────────
# Set to "hashtag" to scrape by hashtag, or "profile" to scrape by username.
SCRAPE_MODE = "hashtag"  # "hashtag" | "profile"
#crochet#crochetersofinstagram#crochetaddict#crochetlove#crochetinspiration#crocheting#handmadecrochet#crochetcommunity#ilovecrochet#makersgonnamake
# ── Hashtag Mode ──
# TARGET_HASHTAGS = ["crochet", "crochetersofinstagram", "crochetaddict", "crochetlove", "crochetinspiration","crocheting","handmadecrochet","crochetcommunity","ilovecrochet","makersgonnamake"]

TARGET_HASHTAGS = ["crochet", "crochetersofinstagram", "crochetaddict"]
POSTS_PER_HASHTAG = 100         # Target number of posts to collect per hashtag
HASHTAG_SCROLL_PAUSE_MIN = 3.0   # Seconds to wait between scroll steps
HASHTAG_SCROLL_PAUSE_MAX = 6.0
IMAGES_ONLY = False              # False = download images AND videos/reels

# ── Profile Mode ──
TARGET_USERNAMES = ["nasa", "natgeo"]
MAX_POSTS_TO_DOWNLOAD = 3

# ──────────────────────────── Auth ─────────────────────────────────────
STORAGE_STATE_PATH = "state.json"
HEADLESS = False
FORCE_RELOGIN = False

# Login Credentials (used for automated login only)
# ⚠️  CHANGE YOUR PASSWORD after state.json is created, then clear these.
IG_USERNAME = "elcianna_6"
IG_PASSWORD = "anncia-elvis0628"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/127.0.0.0 Safari/537.36"
)

# ──────────────────────────── Rate Limiting ─────────────────────────────
POST_DELAY_MIN = 5.0
POST_DELAY_MAX = 10.0

PROFILE_DELAY_MIN = 15.0
PROFILE_DELAY_MAX = 30.0

COOLDOWN_EVERY_N_PROFILES = 5
COOLDOWN_DURATION_MIN = 60.0
COOLDOWN_DURATION_MAX = 120.0

# ──────────────────────────── Comments ──────────────────────────────────
MAX_COMMENTS_PER_POST = 150
COMMENT_SCROLL_PAUSE = 2.5
MAX_COMMENT_SCROLL_ATTEMPTS = 30

# ──────────────────────────── AI Content Filter ──────────────────────────
# Set False to disable filtering (download everything)
AI_FILTER_ENABLED = True

# Posts are skipped if their caption/hashtags contain ANY of these (case-insensitive)
AI_FILTER_HASHTAGS = {
    # ── AI image generators ──
    "midjourney", "midjourneyart", "midjourneyv6", "midjourneyv5",
    "stablediffusion", "stablediffusionart", "sdxl", "sd3",
    "dalle", "dalle2", "dalle3", "openai",
    "leonardoai", "leonardoaiart", "leonardodiffusion",
    "imagineai", "imagineart",
    "adobefirefly", "firefly",
    "ideogram", "ideogramai",
    "playgroundai",
    "flux", "fluxai", "fluxdev", "fluxschnell",
    "nightcafe", "nightcafestudio",
    "bluewillow",
    "bing imageai", "bingimage",
    "canvaai",
    "runwayml", "runway",
    "kling", "klingai",
    "pikaai", "pika",
    "soraai", "sora",
    "novita", "novitaai",
    "dreamstudio",
    "tensorart",
    "civitai",
    "comfyui",
    "automatic1111",
    "promptcraft",
    # ── Generic AI art labels ──
    "aiart", "aiartwork", "aiartcommunity", "aiartist", "aiartdaily",
    "aigenerated", "aiimage", "aiillustration", "aipainting",
    "artificialintelligence", "generativeai", "aicreativity",
    "machinelearning", "mlart", "deeplearning",
    "neuralart", "neuralnetwork", "deepdream",
    "ganart", "diffusionart", "diffusionmodel",
    "promptart", "promptengineering", "texttoimage", "text2image",
    "nijijourney", "niji",
    # ── Video/motion AI ──
    "aianimation", "aivideo", "aifilm",
}

# Caption keyword phrases (checked as substrings, case-insensitive)
AI_FILTER_KEYWORDS = [
    "made with ai", "created with ai", "generated by ai", "ai generated",
    "ai-generated", "ai artwork", "ai art by", "ai image",
    "made using midjourney", "made with midjourney", "created in midjourney",
    "made with stable diffusion", "stable diffusion art",
    "made with dall-e", "dall-e generated", "dalle generated",
    "/imagine prompt", "prompt:", "--ar ", "--v ", "--style ",  # MJ CLI syntax
    "made with firefly", "adobe firefly",
    "made with leonardo", "leonardo ai",
    "made with ideogram",
    "made with flux",
    "this image was generated", "this photo was generated",
    "ai-created", "ai created by",
    "generated with ai", "generated using ai",
    "created using generative ai",
]

# Known AI-art-only accounts (optional — extend as needed)
AI_FILTER_BLOCKED_USERNAMES: set[str] = set()
